### ISSUE TITLE
Create LocalStorage js for homepage

### ISSUE THREAD

**Issue by pmendoza72** [pmendoza72/201-Project#1]

**Comment by 0smium** [comment]
`<!DOCTYPE html>
<html>
  <head>
    <style>
      #nameForm {
        width: 200px;
        margin-left: auto;
        margin-right: auto;
        text-align: center;
      }
      #nameForm fieldset {
        border:1px dashed black;
        margin: 0;
        padding: 10px;
      }
      #nameForm input {
        margin-top: 5px;
      }
    </style>
    <title></title>
  </head>
  <body>
    <form id="nameForm">
      <fieldset>
        <label for="name">Please enter your name</label><br />
        <input type="text" name="name" required><br />
        <input class = "submit" type="submit" value="Done">
      </fieldset>
    </form>
    <script type="text/javascript">
      var nameForm = document.getElementById('nameForm');

      function handleFormSubmit(event) {
        event.preventDefault();
        console.log(event); //Option to log event
        var name = event.target.name.value;

        var stringiedName = JSON.stringify(name);
        localStorage.setItem('stringiedName', stringiedName);

        // Enter URL of where you want to go after submit...
        // location.href="./game.html";
      }

      nameForm.addEventListener('submit', handleFormSubmit);
    </script>
  </body>
</html>`

**Comment by StephenAWalsh** [comment]
Uploaded nameForm.html, which contains HTML, internal CSS, and internal JS.  Functional.
